spring:
  application:
    name: catalog-service
    
  profiles:
    active:
    - common-module  
    - testdata
  
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh
              
server:
  port: 9001

polar:
  greeting: Welcome to the local book catalog!