spring:
  application:
    name: batch-service
          
  mandatory-file-encoding: UTF-8   
            
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
      
  flyway:
    enabled: true
    baseline-version: 1.0
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    target: latest
    locations: classpath:sql/migration
    #url: jdbc:postgresql://ubuntu01:5432/postgres?currentSchema=batch
    #user: postgres
    #password: postgres
    default-schema: batch    
          
  datasource:
    url: jdbc:postgresql://ubuntu01:5432/postgres?currentSchema=batch
    username: postgres
    password: postgres    
    hikari:
      initializationFailTimeout: 60000     
      schema: batch
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
       
  jpa:
    hibernate:
      ddl-auto: validate      
    generate-ddl: false    
    properties:
      hibernate:    
#        generate_statistics: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect #deprecated
    show-sql: true   
    open-in-view: false
      
  sql:
    init:
      platform: postgres
      mode: never   
            
app.csv.fileHeaders: order_ref,amount,order_date,note    