spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dcppsqrb/spring
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          searchPaths: config-repo
          
          
  profiles:
    active:
    - common-module
    
server:
  port: 8888    